#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os, sys
sys.path.append(os.path.join(os.path.dirname(__file__), '.', 'incore'))

# set server timezone in UTC before time module imported
__import__('os').environ['TZ'] = 'UTC'
import incore

if __name__ == "__main__":
    incore.cli.main()

#  vim:et:si:sta:ts=4:sts=4:sw=4:tw=79:
